# Generated by Django 5.1.7 on 2025-03-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_menu_lista_usuarios', 'Puede ver el menú Lista de Usuarios'), ('ver_menu_crear_usuario', 'Puede ver el menú Crear Usuario'), ('ver_menu_asignar_permisos', 'Puede ver el menú Roles y Permisos'), ('puede_crear_usuario', 'Puede crear usuarios'), ('puede_editar_usuario', 'Puede editar usuarios'), ('puede_eliminar_usuario', 'Puede eliminar usuarios')],
            },
        ),
    ]
