# Generated by Django 5.1.7 on 2025-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisodummy',
            options={'permissions': [('ver_menu_lista_usuarios', 'Puede ver el menú Lista de Usuarios'), ('ver_menu_crear_usuario', 'Puede ver el menú Crear Usuario'), ('ver_menu_asignar_permisos', 'Puede ver el menú Roles y Permisos'), ('puede_crear_usuario', 'Puede crear usuarios'), ('puede_editar_usuario', 'Puede editar usuarios'), ('puede_eliminar_usuario', 'Puede eliminar usuarios'), ('ver_menu_bi_financiero', 'Puede ver el menú BI Financiero'), ('ver_menu_bi_operaciones', 'Puede ver el menú BI Operaciones'), ('ver_menu_bi_cait', 'Puede ver el menú BI CAIT'), ('puede_ver_bi_financiero', 'Puede acceder a BI Financiero'), ('puede_ver_bi_operaciones', 'Puede acceder a BI Operaciones'), ('puede_ver_bi_cait', 'Puede acceder a BI CAIT')]},
        ),
    ]
