# Generated by Django 5.1.7 on 2025-10-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_permisodummy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisodummy',
            options={'permissions': [('ver_menu_lista_usuarios', 'Puede ver el menú Lista de Usuarios'), ('ver_menu_crear_usuario', 'Puede ver el menú Crear Usuario'), ('ver_menu_asignar_permisos', 'Puede ver el menú Roles y Permisos'), ('puede_crear_usuario', 'Puede crear usuarios'), ('puede_editar_usuario', 'Puede editar usuarios'), ('puede_eliminar_usuario', 'Puede eliminar usuarios'), ('acceso_bi_financiero', 'Puede ver y acceder a BI Financiero'), ('acceso_bi_operaciones', 'Puede ver y acceder a BI Operaciones'), ('acceso_bi_cait', 'Puede ver y acceder a BI CAIT')]},
        ),
    ]
